# -*- coding: utf-8 -*-
"""DiseasePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOTTbtFeGo7ZdCDll7Jefm4ku5ADwM3o

# Import Libraries & Load Dataset
"""

import pandas as pd
import numpy as np

data = pd.read_csv('medical_dataset_10000.csv')

data.head()

"""# Check Dataset Shape and Info"""

print('shape of the dataset', data.shape)

data.info()

"""# Check Missing Values"""

data.isnull().sum()

"""# Drop Unnecessary Column"""



data.head()

data['Disease'].value_counts()

"""# Encode Gender Column

---
ML models cannot understand text like "Male", "Female", "Other".

"""

from sklearn.preprocessing import LabelEncoder

le_gender = LabelEncoder()
data['Gender'] = le_gender.fit_transform(data['Gender'])

data.head()

"""# Convert Symptoms Text into Numerical Features (TF-IDF)"""

# from sklearn.feature_extraction.text import TfidfVectorizer

# tfidf = TfidfVectorizer(max_features=3000)
# x_symptoms = tfidf.fit_transform(data['Symptoms'])

"""# Extract All Unique Symptoms"""

from sklearn.preprocessing import MultiLabelBinarizer

# Split symptoms into list
data["Symptoms_List"] = data["Symptoms"].apply(lambda x: [s.strip() for s in x.split(",")])

# Create binary symptom matrix
mlb = MultiLabelBinarizer()
X_symptoms = mlb.fit_transform(data["Symptoms_List"])

print("Number of unique symptoms:", len(mlb.classes_))

"""# Combine All Features"""

from scipy.sparse import hstack

x_other = data[['Age', 'Gender', 'Symptom_Count']].values
x = np.hstack([x_other, X_symptoms])

"""# Encode Target (Disease)"""

le_desease = LabelEncoder()
y = le_desease.fit_transform(data['Disease'])

"""# Train Test Split"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42, stratify = y)

"""# Train Random Forest Model"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    random_state=42,
    n_jobs=-1
    )
model.fit(x_train, y_train)

"""# Model Evaluation"""

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(x_test)

print('Accuracy', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""## Save the Model and Tools"""

import joblib

joblib.dump(model, 'model.pkl')
joblib.dump(tfidf, 'tfidf.pkl')
joblib.dump(le_gender, 'le_gender.pkl')
joblib.dump(le_desease, 'le_desease.pkl')